project_name: internvideo #internvideo #CLIP
use_wandb: False

dataset:
  name: htm
  text_type: step # whisperx or step
  mix_dataset: True # when the text_type is step, True for using both whisperx output and howtostep for training
  visual_backbone: internvideo

dataloader:
  phases: ['train','htm-align','ht-step']
  batch_size: 8
  num_workers: 16

model:
  name: detr
  d_model: 256
  d_proj: 64
  nhead: 8
  dropout: 0.1
  enc_layers: 3
  dec_layers: 3
  checkpoint: ''
  save_model: True

criterions: 
  name: similarity
  params: {}

optimizer:
  name: adamw
  init_lr: 1e-4
  weight_decay: 5e-5
  grad_clip: 1.0

scheduler:
  name: cos_decay
  start_epoch: 1
  num_epochs: 20

eval_epochs: 1